/* ALLSTAR GALAXY V2.4 — universal header, navigation, status, hero, footer. */
function active(i,p){return i.id===p.active||(i.matches||[]).includes(p.active)}
function submenu(i){return !i.submenu?.length?'':`<button class="submenu-toggle" type="button" aria-expanded="false" aria-label="Open ${i.label} menu"><span>⌄</span></button><div class="submenu" role="menu">${i.submenu.map(x=>`<a role="menuitem" href="${x.href}">${x.label}</a>`).join('')}</div>`}
function nav(s,p){return s.nav.map(i=>`<div class="nav-item ${active(i,p)?'is-active':''} ${i.id==='search'?'nav-search-item':''}"><a class="nav-link" href="${i.href}" ${active(i,p)?'aria-current="page"':''}>${i.label}</a>${submenu(i)}</div>`).join('')}
export function mountSiteFrame(site,page){
 const host=document.querySelector('#site-frame'),images=Array.isArray(page.hero)?page.hero.map(x=>String(x||'').trim()).filter(Boolean):[];
 host.className='site-frame';
 host.innerHTML=`<header class="shared-header"><div class="identity-row"><a class="brand-home brand-home-left" href="index.html"><img class="brand-logo" src="${site.logo}" alt="Allstar Galaxy"></a><img class="nav-title" src="${page.navTitle}" alt="The Official Home of the Allstar Galaxy"><a class="brand-home brand-home-right" href="index.html"><img class="brand-logo" src="${site.logo}" alt="Allstar Galaxy"></a><a class="search-control" href="search.html"><span>⌕</span><b>Search</b></a></div><nav class="main-nav" aria-label="Main navigation">${nav(site,page)}</nav><div class="status-module"><span class="status-border status-border-top"></span><span class="energy-rail energy-rail-top"><i></i></span><div class="status-bar"><span class="status-icon">${page.icon||'★'}</span><span class="status-text">${page.ticker||''}</span><a class="status-open" href="#main">OPEN →</a></div><span class="energy-rail energy-rail-bottom"><i></i></span><span class="status-border status-border-bottom"></span></div></header>`;
 const hero=document.createElement('section');hero.className='hero';hero.setAttribute('aria-label',`${page.title} hero`);
 hero.innerHTML=images.length?`<div class="hero-track">${images.map((src,i)=>`<img class="hero-slide" src="${src}" alt="${page.title} hero ${i+1}" ${i?'loading="lazy"':'fetchpriority="high"'}>`).join('')}</div><div class="hero-dots">${images.map((_,i)=>`<button class="hero-dot ${i?'':'is-active'}" type="button" aria-label="Show hero ${i+1}" aria-pressed="${!i}" data-index="${i}"></button>`).join('')}</div>`:`<div class="placeholder-panel">Hero image not configured.</div>`;
 host.after(hero);
 const track=hero.querySelector('.hero-track'),dots=[...hero.querySelectorAll('.hero-dot')];let index=0,timer;
 const show=i=>{if(!track||!dots.length)return;index=(i+dots.length)%dots.length;track.style.transform=`translateX(-${index*100}%)`;dots.forEach((d,j)=>{d.classList.toggle('is-active',j===index);d.setAttribute('aria-pressed',String(j===index))})};
 const restart=()=>{clearInterval(timer);if(dots.length>1)timer=setInterval(()=>show(index+1),Number(page.heroInterval)||7000)};
 dots.forEach(d=>d.onclick=()=>{show(+d.dataset.index);restart()});restart();
 const close=e=>host.querySelectorAll('.nav-item.is-open').forEach(x=>{if(x!==e){x.classList.remove('is-open');x.querySelector('.submenu-toggle')?.setAttribute('aria-expanded','false')}});host.querySelectorAll('.submenu-toggle').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const item=b.closest('.nav-item'),open=!item.classList.contains('is-open');close(item);item.classList.toggle('is-open',open);b.setAttribute('aria-expanded',String(open))});document.addEventListener('click',()=>close());document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
}
export function mountFooter(site){
 const h=document.querySelector('#site-footer');h.className='site-footer';
 const socials=(site.footer.social||[]).map(n=>{const href=site.social?.[n]||'#';return`<a href="${href}" ${href==='#'?'':'target="_blank" rel="noopener"'} aria-label="${n}"><img src="assets/images/icons/social/${n}.png" alt=""></a>`}).join('');
 const links=(site.footer.links||[]).map(x=>`<a href="${x.href}">${x.label}</a>`).join('');
 h.innerHTML=`<div class="footer-inner"><section class="footer-brand-block"><strong>${site.footer.credit}</strong><small>Preserving every game, player, and memory.</small></section><nav class="footer-links">${links}</nav><div class="footer-social">${socials}</div><div class="footer-divider"></div><div class="footer-meta"><span>${site.footer.copyright}</span><small>Allstar Galaxy V2.4 • Universal shared framework • GitHub Pages</small></div></div>`;
}