function isActive(item,page){return item.id===page.active||(item.matches||[]).includes(page.active)}
function submenuMarkup(item){if(!item.submenu?.length)return'';return `<button class="submenu-toggle" type="button" aria-expanded="false" aria-label="Open ${item.label} menu">⌄</button><div class="submenu" role="menu">${item.submenu.map(s=>`<a role="menuitem" href="${s.href}">${s.label}</a>`).join('')}</div>`}
export function mountSiteFrame(site,page){
 const host=document.querySelector('#site-frame');host.className='site-frame';
 host.innerHTML=`<header class="shared-header"><div class="identity-row"><img class="brand-logo" src="${site.logo}" alt="Allstar Galaxy"><img class="nav-title" src="${page.navTitle}" alt="The Official Home of the Allstar Galaxy"><a class="search-control" href="search.html" aria-label="Search Allstar Galaxy"><span aria-hidden="true">⌕</span><b>Search</b></a></div><nav class="main-nav" aria-label="Main navigation">${site.nav.map(n=>`<div class="nav-item ${isActive(n,page)?'is-active':''}"><a class="nav-link" href="${n.href}" ${isActive(n,page)?'aria-current="page"':''}>${n.label}</a>${submenuMarkup(n)}</div>`).join('')}</nav><div class="status-bar"><span class="status-icon">${page.icon||'★'}</span><span class="status-text">${page.ticker}</span><a class="status-open" href="#main">OPEN →</a></div></header>`;
 const hero=document.createElement('section');hero.className='hero';hero.setAttribute('aria-label',`${page.title} hero`);hero.innerHTML=`<div class="hero-track">${page.hero.map((src,i)=>`<img class="hero-slide" src="${src}" alt="${page.title} hero ${i+1}">`).join('')}</div><div class="hero-dots">${page.hero.map((_,i)=>`<button class="hero-dot ${i===0?'is-active':''}" aria-label="Show hero ${i+1}" data-index="${i}"></button>`).join('')}</div>`;host.after(hero);
 const track=hero.querySelector('.hero-track'),dots=[...hero.querySelectorAll('.hero-dot')];let index=0,timer;
 const show=i=>{if(!dots.length)return;index=(i+dots.length)%dots.length;track.style.transform=`translateX(-${index*100}%)`;dots.forEach((d,j)=>d.classList.toggle('is-active',j===index))};
 const restart=()=>{clearInterval(timer);if(dots.length>1)timer=setInterval(()=>show(index+1),7000)};dots.forEach(d=>d.addEventListener('click',()=>{show(+d.dataset.index);restart()}));restart();
 const closeAll=except=>host.querySelectorAll('.nav-item.is-open').forEach(x=>{if(x!==except){x.classList.remove('is-open');x.querySelector('.submenu-toggle')?.setAttribute('aria-expanded','false')}});
 host.querySelectorAll('.submenu-toggle').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation();const item=btn.closest('.nav-item'),open=!item.classList.contains('is-open');closeAll(item);item.classList.toggle('is-open',open);btn.setAttribute('aria-expanded',String(open))}));
 document.addEventListener('click',()=>closeAll());document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});
}
export function mountFooter(site){const host=document.querySelector('#site-footer');host.className='site-footer';const icons=site.footer.social.map(name=>`<a href="#" aria-label="${name}"><img src="assets/images/icons/social/${name}.png" alt=""></a>`).join('');const links=(site.footer.links||[]).map(x=>`<a href="${x.href}">${x.label}</a>`).join('');host.innerHTML=`<div class="footer-inner"><div class="footer-credit"><strong>${site.footer.credit}</strong><small>Preserving every game, player, and memory.</small></div><nav class="footer-links" aria-label="Footer navigation">${links}</nav><div class="footer-social">${icons}</div><div class="footer-meta"><span>${site.footer.copyright}</span><small>Allstar Galaxy V2.1 • GitHub Pages</small></div></div>`}
